# Server config
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring config
spring:
  application:
    name: SB app Ec2
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Jpa config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Flyway config
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3366/sb_app_db
    user: user
    password: secret

# CORS config
application:
  cors:
    origins:
      - http://localhost:3000
      - http://localhost:4200
      - http://localhost:5173
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - HEAD
    headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    allow-credentials: false
    max-age: 3600
