# Server config
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring config
spring:
  application:
    name: SB app Ec2
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Docker config
  docker:
    compose:
      enabled: false

  # Datasource config
  datasource:
    url: ${ SPRING_DATASOURCE_URL }
    username: ${ SPRING_DATASOURCE_USERNAME }
    password: ${ SPRING_DATASOURCE_PASSWORD }
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Flyway config
  flyway:
    enabled: ${ SPRING_FLYWAY_ENABLED }
    locations: ${ SPRING_FLYWAY_LOCATIONS }
    baseline-on-migrate: ${ SPRING_FLYWAY_BASELINE_ON_MIGRATION }
    url: ${ SPRING_DATASOURCE_URL }
    username: ${ SPRING_DATASOURCE_USERNAME }
    password: ${ SPRING_DATASOURCE_PASSWORD }

