# Server config
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring config
spring:
  application:
    name: SB app Ec2
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Docker config
  docker:
    compose:
      enabled: false

  # Datasource config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Flyway config
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATION}
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

# CORS config
application:
  cors:
    origins:
      - http://localhost:3000
      - http://localhost:4200
      - http://localhost:5173
      - ${FRONTEND_URL}
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - HEAD
    headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    allow-credentials: true
    max-age: 3600
