CREATE TABLE products
(
    id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL,
    description    TEXT           NOT NULL,
    price          DECIMAL(19, 2) NOT NULL,
    stock_quantity INT,
    category       VARCHAR(50),
    created_at     DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX          idx_product_name (name),
    INDEX          idx_product_category (category)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Add a comment to the table
ALTER TABLE products COMMENT = 'Stores product information including inventory and pricing data';

-- Initialize the table with sample data
INSERT INTO products (name,
                      description,
                      price,
                      stock_quantity,
                      category)
VALUES ('MacBook Pro 16-inch',
        'Apple MacBook Pro with M3 chip, 16GB RAM, 512GB SSD',
        2499.99,
        50,
        'ELECTRONICS'),
       ('Samsung 65" QLED 4K TV',
        '65-inch QLED 4K Smart TV with Alexa built-in',
        1299.99,
        30,
        'ELECTRONICS'),
       ('Men''s Classic Fit Dress Shirt',
        '100% Cotton non-iron dress shirt, available in multiple colors',
        59.95,
        200,
        'CLOTHING'),
       ('Women''s Running Jacket',
        'Lightweight, water-resistant running jacket with reflective details',
        89.95,
        150,
        'CLOTHING'),
       ('The Psychology of Money',
        'Timeless lessons on wealth, greed, and happiness by Morgan Housel',
        19.99,
        100,
        'BOOKS'),
       ('Atomic Habits',
        'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear',
        24.99,
        85,
        'BOOKS'),
       ('Mid-Century Modern Sofa',
        'Comfortable 3-seater sofa with wooden legs and high-quality fabric upholstery',
        899.99,
        15,
        'FURNITURE'),
       ('Adjustable Standing Desk',
        'Electric height-adjustable desk with memory settings and spacious work surface',
        549.99,
        25,
        'FURNITURE'),
       ('Leather Wallet',
        'Genuine leather bifold wallet with RFID blocking technology',
        49.99,
        120,
        'ACCESSORIES'),
       ('Stainless Steel Watch',
        'Waterproof stainless steel watch with automatic movement',
        299.99,
        40,
        'ACCESSORIES');
